// Generated by CoffeeScript 1.4.0
(function() {
  var converter;

  window.App = Ember.Application.create({
    LOG_TRANSITIONS: true
  });

  App.Store = DS.Store.extend({
    revision: 12,
    adapter: DS.RESTAdapter.extend({
      url: "http://localhost:9292"
    })
  });

  App.Router.map(function() {
    this.route('about');
    return this.resource('posts', function() {
      return this.resource('post', {
        path: ':post_id'
      });
    });
  });

  App.PostsRoute = Ember.Route.extend({
    model: function() {
      return App.Post.find();
    }
  });

  App.Post = DS.Model.extend({
    title: DS.attr('string'),
    author: DS.attr('string'),
    intro: DS.attr('string'),
    description: DS.attr('string'),
    publishedAt: DS.attr('date')
  });

  App.ApplicationController = Em.Controller.extend({
    title: 'MakLog'
  });

  Em.Handlebars.registerBoundHelper('date', function(date) {
    return moment(date).fromNow();
  });

  converter = new Showdown.converter();

  Em.Handlebars.registerBoundHelper('markdown', function(input) {
    return Em.Handlebars.SafeString(converter.makeHtml(input));
  });

}).call(this);
